services:
  backend:
    image: blogs-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      MONGO_URL: mongodb://root:example@mongo:27017/the_database?authSource=admin
    depends_on:
      - mongo
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    container_name: blogs-backend

  nginx:
    image: nginx:1.29
    container_name: reverse-proxy
    ports:
      - 8080:80
    depends_on:
      - backend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
  
  mongo:
    image: mongo
    ports:
      - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - mongo_data:/data/db

  debug-helper:
    image: busybox

volumes:
  mongo_data: