@baseUrl = http://localhost:3003/api/blogs
@blogId = 69b805fe55e122f2e9525df1

###
GET {{baseUrl}}

###
GET {{baseUrl}}/{{blogId}}

###
POST {{baseUrl}}
Content-Type: application/json

{
    "title": "new Blog",
    "author": "Blog Author",
    "url": "Blog url",
    "likes": 10,
}

###
PUT {{baseUrl}}/{{blogId}}
Content-Type: application/json

{
    "title": "updated Blog",
    "author": "Blog Author",
    "url": "Blog url",
    "likes": 13,
}
###
DELETE {{baseUrl}}/{{blogId}}